version: '3.8'

services:
  xray-proxy:
    build: .
    container_name: xray-proxy
    image: xray-tun2socks-arm
    restart: unless-stopped
    network_mode: host
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - SERVER_PORT=${SERVER_PORT}
      - USER_ID=${USER_ID}
      - ENCRYPTION=${ENCRYPTION}
      - FINGERPRINT_FP=${FINGERPRINT_FP}
      - FLOW=${FLOW}
      - SERVER_NAME_SNI=${SERVER_NAME_SNI}
      - PUBLIC_KEY_PBK=${PUBLIC_KEY_PBK}
      - SHORT_ID=${SHORT_ID}
      - GATEWAY=${GATEWAY}
      - ADAPTER_NAME=${ADAPTER_NAME}
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    volumes:
      - "/dev/net/tun:/dev/net/tun"
    privileged: true
    command: /bin/sh -c "/app/start.sh && tail -f /dev/null"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
